book/urls.py
from django.urls import path
from . import views 

app_name = 'book' 

urlpatterns = [
    path('', views.BookListView.as_view(), name='list'), 
    path('detail/<int:pk>/', views.BookDetailView.as_view(), name='detail'), 
    path('create/', views.BookCreateView.as_view(), name='create'), 
    path('update/<int:pk>/', views.BookUpdateView.as_view(), name='update'), 
    path('delete/<int:pk>/', views.BookDeleteView.as_view(), name='delete'),
    path('rlist/', views.ReferenceListView.as_view(), name='rlist'), 
    path('rdetail/<int:pk>/', views.ReferenceDetailView.as_view(), name='rdetail'), 
    path('rcreate/', views.ReferenceCreateView.as_view(), name='rcreate'), 
    path('rupdate/<int:pk>/', views.ReferenceUpdateView.as_view(), name='rupdate'), 
    path('rdelete/<int:pk>/', views.ReferenceDeleteView.as_view(), name='rdelete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('book.urls')),
]

book/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Book(models.Model):
    """書籍"""
    book = models.CharField('書籍名', max_length=255)
    author = models.CharField('著者名', max_length=255, blank=True)
    publisher = models.CharField('出版社', max_length=255, blank=True)
    year = models.CharField('発行年', max_length=20,blank=True)
    page = models.CharField('ページ数', max_length=20,blank=True)
    remarks = models.TextField('備考',max_length=1000,blank=True)

    def __str__(self):
        return self.book

class Reference(models.Model):
    """論文"""
    reference = models.CharField("タイトル", max_length=255)
    site = models.CharField('サイト', max_length=255, blank=True)
    url = models.CharField("URL", max_length=500, blank=True)
    day = models.CharField("閲覧日", max_length=50,blank=True)
    remarks_ref = models.TextField('備考',max_length=1000,blank=True)


    def __str__(self):
        return self.reference

book/forms.py
from django import forms
from .models import Book
from .models import Reference

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ('page','remarks',)

class ReferenceForm(forms.ModelForm):
    class Meta:
        model = Reference
        exclude = ('remarks_ref',) 

book/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Book
from .forms import BookForm
from .models import Reference
from .forms import ReferenceForm
from django.shortcuts import render, redirect
from django.http import HttpResponse

# 参考文献の一覧表示機能
class BookListView(generic.ListView):
    model = Book
    paginate_by = 5

# 参考文献の詳細表示機能
class BookDetailView(generic.DetailView):
    model = Book

# ToDoの作成機能
class BookCreateView(generic.CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('book:list')

# ToDoの編集機能
class BookUpdateView(generic.UpdateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('book:list')

# ToDoの削除機能
class BookDeleteView(generic.DeleteView):
    model = Book
    success_url = reverse_lazy('book:list')


def book_list(request):
    """書籍の一覧"""
    books = Book.objects.all().order_by('id')
    return render(request,
                  'book/book_list.html',     # 使用するテンプレート
                  {'books': books})         # テンプレートに渡すデータ


# 参考文献の一覧表示機能
class ReferenceListView(generic.ListView):
    model = Reference
    paginate_by = 5

# 参考文献の詳細表示機能
class ReferenceDetailView(generic.DetailView):
    model = Reference

# ToDoの作成機能
class ReferenceCreateView(generic.CreateView):
    model = Reference
    form_class = ReferenceForm
    success_url = reverse_lazy('book:rlist')

# ToDoの編集機能
class ReferenceUpdateView(generic.UpdateView):
    model = Reference
    form_class = ReferenceForm
    success_url = reverse_lazy('book:rlist')

# ToDoの削除機能
class ReferenceDeleteView(generic.DeleteView):
    model = Reference
    success_url = reverse_lazy('book:rlist')


def reference(request):
    """書籍の一覧"""
    references = Reference.objects.all().order_by('id')
    return render(request,
                  'book/reference.html',     # 使用するテンプレート
                  {'references': references})         # テンプレートに渡すデータ

book/templates/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'book/css/bootstrap.min.css' %}">
  {% block extra_css %}{% endblock %}
  <title>{% block title %}参考文献リスト{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'book:list' %}">書籍</a>
        </li>
      </ul>
    </div>
  


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'book:rlist' %}">ネット</a>
        </li>
      </ul>
    </div>
  </nav>


    <br>
    <div class="container">
      {% block content %}
      {{ content }}
      {% endblock %}
    </div>
  <script src="{% static 'book/js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'book/js/bootstrap.bundle.min.js' %}"></script>
  
  {% block extra_js %}{% endblock %}
</body>
</html>

book/templates/book/book_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>文献の削除</h1>
<table>
    <tr>
        <th>タイトル</th>
        <td>{{ object.book }}</td>
    </tr>
    <tr>
        <th>著者名</th>
        <td>{{ object.author }}</td>
    </tr>
    <tr>
        <th>出版社</th>
        <td>{{ object.publisher }}</td>
    </tr>
      <tr>
        <th>年</th>
        <td>{{ object.year }}</td>
    </tr>
    <tr>
        <th>該当ページ</th>
        <td>{{ object.page }}</td>
    </tr>
</table>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit"value="削除" />
</form>
<a href="{% url 'book:list' %}">戻る</a>
{%endblock%}

book/templates/book/book_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>本の詳細</h1>
<table>
    <tr>
        <th>ID</th>
        <td>{{ object.id }}</td>
    </tr>
    <tr>
        <th>タイトル</th>
        <td>{{ object.book }}</td>
    </tr>
    <tr>
        <th>著者</th>
        <td>{{ object.author }}</td>
    </tr>
    <tr>
        <th>出版社</th>
        <td>{{ object.publisher }}</td>
    </tr>
    <tr>
        <th>発行年</th>
        <td>{{ object.year }}</td>
    </tr>
    <tr>
        <th>該当ページ</th>
        <td>{{ object.page }}</td>
    </tr>
     <tr>
        <th>備考</th>
        <td>{{ object.remarks }}</td>
    </tr>
</table>
<a href="{% url 'book:list' %}">戻る</a>
{%endblock%}

book/templates/book/book_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>参考文献（書籍）編集</h1>
{% else %}
<h1>参考文献(書籍）作成</h1>
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form }} 
    <button type="submit">送信</button>
</form>
<a href="{% url 'book:list' %}">戻る</a>
{%endblock%}

book/templates/book/book_list.html
{% extends 'base.html' %}

{% block title %}参考文献リスト{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">参考文献一覧(書籍)</h4>
{% if user.is_authenticated %}  
  <a href="{% url 'book:create' %}">追加</a>
{% endif %}
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">書籍名</th>
      <th scope="col">著者名</th>
      <th scope="col">出版社</th>
      <th scope="col">発行年</th>
    </tr>
  </thead>
  <tbody>
    {% for item in object_list %}
    <tr>
      <td>{{ item.book }}</td>
      <td>{{ item.author }}</td>
      <td>{{ item.publisher }}</td>
      <td>{{ item.year }}</td>
      <td>
        {% if user.is_authenticated %}
          <a href="{% url 'book:update' pk=item.id %}">修正</a>
          <a href="{% url 'book:delete' pk=item.id %}">削除</a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{%endblock%}

book/templates/book/create.html
<!DOCTYPE html>
<html lang="ja">
  <body>
    <form method="POST" action="{% url 'create_account' %}">
      {% csrf_token %}
      <label>ユーザーID</label>
      {{ form.username }}
      {{ form.username.errors }}
      <label>パスワード</label>
      {{ form.password1 }}
      {{ form.password1.errors }}
      <label>パスワード(確認)</label>
      {{ form.password2 }}
      {{ form.password2.errors }}
      <button type = "submit">登録</button>
    </form>
  </body>
</html>

book/templates/book/index.html
<!DOCTYPE html>
<html lang="ja">
  <body>
    {% if user.id  %}
    <p>ログインしました．</p>
    <p>こんにちは，{{ user.username }}さん</p>
    <a href="{% url 'logout' %}">ログアウトする</a>
    {% else %}
    <a href="{% url 'login' %}">ログイン</a>
    <a href="{% url 'create_account' %}">アカウント作成</a>
    {% endif %}
  </body>
</html>

book/templates/book/login.html
<!DOCTYPE html>
<html lang="ja">
  <body>
    {% if form.errors  %}
    <p>ユーザーID, パスワードが一致しません．</p>
    {% endif %}
    <form method="POST" action="{% url 'login' %}">
      {% csrf_token %}
      <label>ユーザーID</label>
      {{ form.username }}
      {{ form.username.errors }}
      <label>パスワード</label>
      {{ form.password }}
      {{ form.password.errors }}
      <button type = "submit">ログイン</button>
    </form>
  </body>
</html>

book/templates/book/reference_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>文献（ネット）の削除</h1>
<table>
    <tr>
        <th>タイトル</th>
        <td>{{ object.reference }}</td>
    </tr>
    <tr>
        <th>サイト名</th>
        <td>{{ object.site }}</td>
    </tr>
    <tr>
        <th>URL</th>
        <td>{{ object.url }}</td>
    </tr>
      <tr>
        <th>閲覧日</th>
        <td>{{ object.day }}</td>
    </tr>
</table>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit"value="削除" />
</form>
<a href="{% url 'book:rlist' %}">戻る</a>
{%endblock%}

book/templates/book/reference_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>サイトの詳細</h1>
<table>
    <tr>
        <th>ID</th>
        <td>{{ object.id }}</td>
    </tr>
    <tr>
        <th>タイトル</th>
        <td>{{ object.reference }}</td>
    </tr>
    <tr>
        <th>サイト名</th>
        <td>{{ object.site }}</td>
    </tr>
    <tr>
        <th>URL</th>
        <td>{{ object.url }}</td>
    </tr>
    <tr>
        <th>閲覧日</th>
        <td>{{ object.day }}</td>
    </tr>
    <tr>
        <th>該当ページ</th>
        <td>{{ object.page }}</td>
    </tr>
     <tr>
        <th>備考</th>
        <td>{{ object.remarks }}</td>
    </tr>
</table>
<a href="{% url 'book:rlist' %}">戻る</a>
{%endblock%}

book/templates/book/reference_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>参考文献（ネット）編集</h1>
{% else %}
<h1>参考文献（ネット）作成</h1>
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form }} 
    <button type="submit">送信</button>
</form>
<a href="{% url 'book:rlist' %}">戻る</a>
{%endblock%}

book/templates/book/reference_list.html
{% extends 'base.html' %}

{% block title %}参考文献リスト{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">参考文献一覧(オンライン)</h4>
{% if user.is_authenticated %} 
  <a href="{% url 'book:rcreate' %}">追加</a>
{% endif %}
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">サイト名</th>
      <th scope="col">URL</th>
      <th scope="col">閲覧日</th>
    </tr>
  </thead>
  <tbody>
    {% for item in object_list %}
    <tr>
      <td>{{ item.reference }}</td>
      <td>{{ item.site }}</td>
      <td>{{ item.url }}</td>
      <td>{{ item.day }}</td>
      <td>
        {% if user.is_authenticated %} 
          <a href="{% url 'book:rupdate' pk=item.id %}">修正</a>
          <a href="{% url 'book:rdelete' pk=item.id %}">削除</a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{%endblock%}